/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.StratificationMethod;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Stratification Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StratificationMethodImpl extends MinimalEObjectImpl.Container implements StratificationMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StratificationMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.STRATIFICATION_METHOD;
  }

} //StratificationMethodImpl
