/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMmlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MmlIdeModule extends AbstractMmlIdeModule {
}
