/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.mml;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlFactory
 * @model kind="package"
 * @generated
 */
public interface MmlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mml";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Mml";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mml";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MmlPackage eINSTANCE = org.xtext.example.mydsl.mml.impl.MmlPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.MMLModelImpl <em>MML Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.MMLModelImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMMLModel()
   * @generated
   */
  int MML_MODEL = 0;

  /**
   * The feature id for the '<em><b>Pream</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__PREAM = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__INPUT = 1;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__ALGORITHM = 2;

  /**
   * The feature id for the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__FORMULA = 3;

  /**
   * The feature id for the '<em><b>Validation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__VALIDATION = 4;

  /**
   * The number of structural features of the '<em>MML Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.PREAMBULEImpl <em>PREAMBULE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.PREAMBULEImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getPREAMBULE()
   * @generated
   */
  int PREAMBULE = 1;

  /**
   * The feature id for the '<em><b>Nom Programme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULE__NOM_PROGRAMME = 0;

  /**
   * The number of structural features of the '<em>PREAMBULE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.DataInputImpl <em>Data Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.DataInputImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDataInput()
   * @generated
   */
  int DATA_INPUT = 2;

  /**
   * The feature id for the '<em><b>Filelocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_INPUT__FILELOCATION = 0;

  /**
   * The feature id for the '<em><b>Parsing Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_INPUT__PARSING_INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Data Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_INPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.CSVParsingConfigurationImpl <em>CSV Parsing Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.CSVParsingConfigurationImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCSVParsingConfiguration()
   * @generated
   */
  int CSV_PARSING_CONFIGURATION = 3;

  /**
   * The feature id for the '<em><b>Sep</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_PARSING_CONFIGURATION__SEP = 0;

  /**
   * The number of structural features of the '<em>CSV Parsing Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_PARSING_CONFIGURATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.MLChoiceAlgorithmImpl <em>ML Choice Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.MLChoiceAlgorithmImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMLChoiceAlgorithm()
   * @generated
   */
  int ML_CHOICE_ALGORITHM = 4;

  /**
   * The feature id for the '<em><b>Framework</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_CHOICE_ALGORITHM__FRAMEWORK = 0;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_CHOICE_ALGORITHM__ALGORITHM = 1;

  /**
   * The number of structural features of the '<em>ML Choice Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_CHOICE_ALGORITHM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.MLAlgorithmImpl <em>ML Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.MLAlgorithmImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMLAlgorithm()
   * @generated
   */
  int ML_ALGORITHM = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_ALGORITHM__NAME = 0;

  /**
   * The number of structural features of the '<em>ML Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_ALGORITHM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.SVMImpl <em>SVM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.SVMImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVM()
   * @generated
   */
  int SVM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__NAME = ML_ALGORITHM__NAME;

  /**
   * The feature id for the '<em><b>Gamma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__GAMMA = ML_ALGORITHM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__C = ML_ALGORITHM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Kernel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__KERNEL = ML_ALGORITHM_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Svmclassification</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__SVMCLASSIFICATION = ML_ALGORITHM_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>SVM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM_FEATURE_COUNT = ML_ALGORITHM_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.DTImpl <em>DT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.DTImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDT()
   * @generated
   */
  int DT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__NAME = ML_ALGORITHM__NAME;

  /**
   * The feature id for the '<em><b>Max depth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__MAX_DEPTH = ML_ALGORITHM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>DT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT_FEATURE_COUNT = ML_ALGORITHM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.RandomForestImpl <em>Random Forest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.RandomForestImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getRandomForest()
   * @generated
   */
  int RANDOM_FOREST = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST__NAME = ML_ALGORITHM__NAME;

  /**
   * The feature id for the '<em><b>Ntree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST__NTREE = ML_ALGORITHM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Random Forest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST_FEATURE_COUNT = ML_ALGORITHM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.LogisticRegressionImpl <em>Logistic Regression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.LogisticRegressionImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getLogisticRegression()
   * @generated
   */
  int LOGISTIC_REGRESSION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGISTIC_REGRESSION__NAME = ML_ALGORITHM__NAME;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGISTIC_REGRESSION__CLASS = ML_ALGORITHM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Logistic Regression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGISTIC_REGRESSION_FEATURE_COUNT = ML_ALGORITHM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.RFormulaImpl <em>RFormula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.RFormulaImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getRFormula()
   * @generated
   */
  int RFORMULA = 10;

  /**
   * The feature id for the '<em><b>Predictive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RFORMULA__PREDICTIVE = 0;

  /**
   * The feature id for the '<em><b>Predictors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RFORMULA__PREDICTORS = 1;

  /**
   * The number of structural features of the '<em>RFormula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RFORMULA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.XFormulaImpl <em>XFormula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.XFormulaImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getXFormula()
   * @generated
   */
  int XFORMULA = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XFORMULA__NAME = 0;

  /**
   * The number of structural features of the '<em>XFormula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XFORMULA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.AllVariablesImpl <em>All Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.AllVariablesImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getAllVariables()
   * @generated
   */
  int ALL_VARIABLES = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_VARIABLES__NAME = XFORMULA__NAME;

  /**
   * The feature id for the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_VARIABLES__ALL = XFORMULA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>All Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_VARIABLES_FEATURE_COUNT = XFORMULA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.PredictorVariablesImpl <em>Predictor Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.PredictorVariablesImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getPredictorVariables()
   * @generated
   */
  int PREDICTOR_VARIABLES = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTOR_VARIABLES__NAME = XFORMULA__NAME;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTOR_VARIABLES__VARS = XFORMULA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predictor Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTOR_VARIABLES_FEATURE_COUNT = XFORMULA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.FormulaItemImpl <em>Formula Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.FormulaItemImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getFormulaItem()
   * @generated
   */
  int FORMULA_ITEM = 14;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_ITEM__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Col Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_ITEM__COL_NAME = 1;

  /**
   * The number of structural features of the '<em>Formula Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.ValidationImpl <em>Validation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.ValidationImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getValidation()
   * @generated
   */
  int VALIDATION = 15;

  /**
   * The feature id for the '<em><b>Stratification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__STRATIFICATION = 0;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__METRIC = 1;

  /**
   * The number of structural features of the '<em>Validation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.StratificationMethodImpl <em>Stratification Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.StratificationMethodImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getStratificationMethod()
   * @generated
   */
  int STRATIFICATION_METHOD = 16;

  /**
   * The number of structural features of the '<em>Stratification Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATIFICATION_METHOD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.TrainingTestImpl <em>Training Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.TrainingTestImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getTrainingTest()
   * @generated
   */
  int TRAINING_TEST = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST__NAME = STRATIFICATION_METHOD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST__NUMBER = STRATIFICATION_METHOD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Training Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST_FEATURE_COUNT = STRATIFICATION_METHOD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.CSVSeparator <em>CSV Separator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.CSVSeparator
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCSVSeparator()
   * @generated
   */
  int CSV_SEPARATOR = 18;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.FrameworkLang <em>Framework Lang</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.FrameworkLang
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getFrameworkLang()
   * @generated
   */
  int FRAMEWORK_LANG = 19;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.SVMKernel <em>SVM Kernel</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.SVMKernel
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVMKernel()
   * @generated
   */
  int SVM_KERNEL = 20;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.SVMClassification <em>SVM Classification</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.SVMClassification
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVMClassification()
   * @generated
   */
  int SVM_CLASSIFICATION = 21;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.CLASS <em>CLASS</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.CLASS
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCLASS()
   * @generated
   */
  int CLASS = 22;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.ValidationMetric <em>Validation Metric</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.ValidationMetric
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getValidationMetric()
   * @generated
   */
  int VALIDATION_METRIC = 23;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.MMLModel <em>MML Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MML Model</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel
   * @generated
   */
  EClass getMMLModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getPream <em>Pream</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pream</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getPream()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Pream();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getInput()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Input();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algorithm</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getAlgorithm()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Algorithm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getFormula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formula</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getFormula()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Formula();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getValidation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Validation</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getValidation()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Validation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.PREAMBULE <em>PREAMBULE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PREAMBULE</em>'.
   * @see org.xtext.example.mydsl.mml.PREAMBULE
   * @generated
   */
  EClass getPREAMBULE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.PREAMBULE#getNomProgramme <em>Nom Programme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom Programme</em>'.
   * @see org.xtext.example.mydsl.mml.PREAMBULE#getNomProgramme()
   * @see #getPREAMBULE()
   * @generated
   */
  EAttribute getPREAMBULE_NomProgramme();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.DataInput <em>Data Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Input</em>'.
   * @see org.xtext.example.mydsl.mml.DataInput
   * @generated
   */
  EClass getDataInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.DataInput#getFilelocation <em>Filelocation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filelocation</em>'.
   * @see org.xtext.example.mydsl.mml.DataInput#getFilelocation()
   * @see #getDataInput()
   * @generated
   */
  EAttribute getDataInput_Filelocation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.DataInput#getParsingInstruction <em>Parsing Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parsing Instruction</em>'.
   * @see org.xtext.example.mydsl.mml.DataInput#getParsingInstruction()
   * @see #getDataInput()
   * @generated
   */
  EReference getDataInput_ParsingInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.CSVParsingConfiguration <em>CSV Parsing Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSV Parsing Configuration</em>'.
   * @see org.xtext.example.mydsl.mml.CSVParsingConfiguration
   * @generated
   */
  EClass getCSVParsingConfiguration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.CSVParsingConfiguration#getSep <em>Sep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sep</em>'.
   * @see org.xtext.example.mydsl.mml.CSVParsingConfiguration#getSep()
   * @see #getCSVParsingConfiguration()
   * @generated
   */
  EAttribute getCSVParsingConfiguration_Sep();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.MLChoiceAlgorithm <em>ML Choice Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ML Choice Algorithm</em>'.
   * @see org.xtext.example.mydsl.mml.MLChoiceAlgorithm
   * @generated
   */
  EClass getMLChoiceAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.MLChoiceAlgorithm#getFramework <em>Framework</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Framework</em>'.
   * @see org.xtext.example.mydsl.mml.MLChoiceAlgorithm#getFramework()
   * @see #getMLChoiceAlgorithm()
   * @generated
   */
  EAttribute getMLChoiceAlgorithm_Framework();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MLChoiceAlgorithm#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algorithm</em>'.
   * @see org.xtext.example.mydsl.mml.MLChoiceAlgorithm#getAlgorithm()
   * @see #getMLChoiceAlgorithm()
   * @generated
   */
  EReference getMLChoiceAlgorithm_Algorithm();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.MLAlgorithm <em>ML Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ML Algorithm</em>'.
   * @see org.xtext.example.mydsl.mml.MLAlgorithm
   * @generated
   */
  EClass getMLAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.MLAlgorithm#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.mml.MLAlgorithm#getName()
   * @see #getMLAlgorithm()
   * @generated
   */
  EAttribute getMLAlgorithm_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.SVM <em>SVM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SVM</em>'.
   * @see org.xtext.example.mydsl.mml.SVM
   * @generated
   */
  EClass getSVM();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.SVM#getGamma <em>Gamma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gamma</em>'.
   * @see org.xtext.example.mydsl.mml.SVM#getGamma()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_Gamma();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.SVM#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>C</em>'.
   * @see org.xtext.example.mydsl.mml.SVM#getC()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_C();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.SVM#getKernel <em>Kernel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kernel</em>'.
   * @see org.xtext.example.mydsl.mml.SVM#getKernel()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_Kernel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.SVM#getSvmclassification <em>Svmclassification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Svmclassification</em>'.
   * @see org.xtext.example.mydsl.mml.SVM#getSvmclassification()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_Svmclassification();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.DT <em>DT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DT</em>'.
   * @see org.xtext.example.mydsl.mml.DT
   * @generated
   */
  EClass getDT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.DT#getMax_depth <em>Max depth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max depth</em>'.
   * @see org.xtext.example.mydsl.mml.DT#getMax_depth()
   * @see #getDT()
   * @generated
   */
  EAttribute getDT_Max_depth();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.RandomForest <em>Random Forest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Random Forest</em>'.
   * @see org.xtext.example.mydsl.mml.RandomForest
   * @generated
   */
  EClass getRandomForest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.RandomForest#getNtree <em>Ntree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ntree</em>'.
   * @see org.xtext.example.mydsl.mml.RandomForest#getNtree()
   * @see #getRandomForest()
   * @generated
   */
  EAttribute getRandomForest_Ntree();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.LogisticRegression <em>Logistic Regression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logistic Regression</em>'.
   * @see org.xtext.example.mydsl.mml.LogisticRegression
   * @generated
   */
  EClass getLogisticRegression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.LogisticRegression#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class</em>'.
   * @see org.xtext.example.mydsl.mml.LogisticRegression#getClass_()
   * @see #getLogisticRegression()
   * @generated
   */
  EAttribute getLogisticRegression_Class();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.RFormula <em>RFormula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RFormula</em>'.
   * @see org.xtext.example.mydsl.mml.RFormula
   * @generated
   */
  EClass getRFormula();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.RFormula#getPredictive <em>Predictive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predictive</em>'.
   * @see org.xtext.example.mydsl.mml.RFormula#getPredictive()
   * @see #getRFormula()
   * @generated
   */
  EReference getRFormula_Predictive();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.RFormula#getPredictors <em>Predictors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predictors</em>'.
   * @see org.xtext.example.mydsl.mml.RFormula#getPredictors()
   * @see #getRFormula()
   * @generated
   */
  EReference getRFormula_Predictors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.XFormula <em>XFormula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XFormula</em>'.
   * @see org.xtext.example.mydsl.mml.XFormula
   * @generated
   */
  EClass getXFormula();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.XFormula#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.mml.XFormula#getName()
   * @see #getXFormula()
   * @generated
   */
  EAttribute getXFormula_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.AllVariables <em>All Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Variables</em>'.
   * @see org.xtext.example.mydsl.mml.AllVariables
   * @generated
   */
  EClass getAllVariables();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.AllVariables#getAll <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>All</em>'.
   * @see org.xtext.example.mydsl.mml.AllVariables#getAll()
   * @see #getAllVariables()
   * @generated
   */
  EAttribute getAllVariables_All();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.PredictorVariables <em>Predictor Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predictor Variables</em>'.
   * @see org.xtext.example.mydsl.mml.PredictorVariables
   * @generated
   */
  EClass getPredictorVariables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mml.PredictorVariables#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.xtext.example.mydsl.mml.PredictorVariables#getVars()
   * @see #getPredictorVariables()
   * @generated
   */
  EReference getPredictorVariables_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.FormulaItem <em>Formula Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formula Item</em>'.
   * @see org.xtext.example.mydsl.mml.FormulaItem
   * @generated
   */
  EClass getFormulaItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.FormulaItem#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see org.xtext.example.mydsl.mml.FormulaItem#getColumn()
   * @see #getFormulaItem()
   * @generated
   */
  EAttribute getFormulaItem_Column();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.FormulaItem#getColName <em>Col Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col Name</em>'.
   * @see org.xtext.example.mydsl.mml.FormulaItem#getColName()
   * @see #getFormulaItem()
   * @generated
   */
  EAttribute getFormulaItem_ColName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.Validation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validation</em>'.
   * @see org.xtext.example.mydsl.mml.Validation
   * @generated
   */
  EClass getValidation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.Validation#getStratification <em>Stratification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stratification</em>'.
   * @see org.xtext.example.mydsl.mml.Validation#getStratification()
   * @see #getValidation()
   * @generated
   */
  EReference getValidation_Stratification();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.mml.Validation#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Metric</em>'.
   * @see org.xtext.example.mydsl.mml.Validation#getMetric()
   * @see #getValidation()
   * @generated
   */
  EAttribute getValidation_Metric();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.StratificationMethod <em>Stratification Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stratification Method</em>'.
   * @see org.xtext.example.mydsl.mml.StratificationMethod
   * @generated
   */
  EClass getStratificationMethod();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.TrainingTest <em>Training Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training Test</em>'.
   * @see org.xtext.example.mydsl.mml.TrainingTest
   * @generated
   */
  EClass getTrainingTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.TrainingTest#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.mml.TrainingTest#getName()
   * @see #getTrainingTest()
   * @generated
   */
  EAttribute getTrainingTest_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.TrainingTest#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl.mml.TrainingTest#getNumber()
   * @see #getTrainingTest()
   * @generated
   */
  EAttribute getTrainingTest_Number();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.CSVSeparator <em>CSV Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>CSV Separator</em>'.
   * @see org.xtext.example.mydsl.mml.CSVSeparator
   * @generated
   */
  EEnum getCSVSeparator();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.FrameworkLang <em>Framework Lang</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Framework Lang</em>'.
   * @see org.xtext.example.mydsl.mml.FrameworkLang
   * @generated
   */
  EEnum getFrameworkLang();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.SVMKernel <em>SVM Kernel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SVM Kernel</em>'.
   * @see org.xtext.example.mydsl.mml.SVMKernel
   * @generated
   */
  EEnum getSVMKernel();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.SVMClassification <em>SVM Classification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SVM Classification</em>'.
   * @see org.xtext.example.mydsl.mml.SVMClassification
   * @generated
   */
  EEnum getSVMClassification();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.CLASS <em>CLASS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>CLASS</em>'.
   * @see org.xtext.example.mydsl.mml.CLASS
   * @generated
   */
  EEnum getCLASS();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.mml.ValidationMetric <em>Validation Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Validation Metric</em>'.
   * @see org.xtext.example.mydsl.mml.ValidationMetric
   * @generated
   */
  EEnum getValidationMetric();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MmlFactory getMmlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.MMLModelImpl <em>MML Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.MMLModelImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMMLModel()
     * @generated
     */
    EClass MML_MODEL = eINSTANCE.getMMLModel();

    /**
     * The meta object literal for the '<em><b>Pream</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__PREAM = eINSTANCE.getMMLModel_Pream();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__INPUT = eINSTANCE.getMMLModel_Input();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__ALGORITHM = eINSTANCE.getMMLModel_Algorithm();

    /**
     * The meta object literal for the '<em><b>Formula</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__FORMULA = eINSTANCE.getMMLModel_Formula();

    /**
     * The meta object literal for the '<em><b>Validation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__VALIDATION = eINSTANCE.getMMLModel_Validation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.PREAMBULEImpl <em>PREAMBULE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.PREAMBULEImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getPREAMBULE()
     * @generated
     */
    EClass PREAMBULE = eINSTANCE.getPREAMBULE();

    /**
     * The meta object literal for the '<em><b>Nom Programme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREAMBULE__NOM_PROGRAMME = eINSTANCE.getPREAMBULE_NomProgramme();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.DataInputImpl <em>Data Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.DataInputImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDataInput()
     * @generated
     */
    EClass DATA_INPUT = eINSTANCE.getDataInput();

    /**
     * The meta object literal for the '<em><b>Filelocation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_INPUT__FILELOCATION = eINSTANCE.getDataInput_Filelocation();

    /**
     * The meta object literal for the '<em><b>Parsing Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_INPUT__PARSING_INSTRUCTION = eINSTANCE.getDataInput_ParsingInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.CSVParsingConfigurationImpl <em>CSV Parsing Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.CSVParsingConfigurationImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCSVParsingConfiguration()
     * @generated
     */
    EClass CSV_PARSING_CONFIGURATION = eINSTANCE.getCSVParsingConfiguration();

    /**
     * The meta object literal for the '<em><b>Sep</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV_PARSING_CONFIGURATION__SEP = eINSTANCE.getCSVParsingConfiguration_Sep();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.MLChoiceAlgorithmImpl <em>ML Choice Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.MLChoiceAlgorithmImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMLChoiceAlgorithm()
     * @generated
     */
    EClass ML_CHOICE_ALGORITHM = eINSTANCE.getMLChoiceAlgorithm();

    /**
     * The meta object literal for the '<em><b>Framework</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ML_CHOICE_ALGORITHM__FRAMEWORK = eINSTANCE.getMLChoiceAlgorithm_Framework();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_CHOICE_ALGORITHM__ALGORITHM = eINSTANCE.getMLChoiceAlgorithm_Algorithm();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.MLAlgorithmImpl <em>ML Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.MLAlgorithmImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMLAlgorithm()
     * @generated
     */
    EClass ML_ALGORITHM = eINSTANCE.getMLAlgorithm();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ML_ALGORITHM__NAME = eINSTANCE.getMLAlgorithm_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.SVMImpl <em>SVM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.SVMImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVM()
     * @generated
     */
    EClass SVM = eINSTANCE.getSVM();

    /**
     * The meta object literal for the '<em><b>Gamma</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__GAMMA = eINSTANCE.getSVM_Gamma();

    /**
     * The meta object literal for the '<em><b>C</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__C = eINSTANCE.getSVM_C();

    /**
     * The meta object literal for the '<em><b>Kernel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__KERNEL = eINSTANCE.getSVM_Kernel();

    /**
     * The meta object literal for the '<em><b>Svmclassification</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__SVMCLASSIFICATION = eINSTANCE.getSVM_Svmclassification();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.DTImpl <em>DT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.DTImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDT()
     * @generated
     */
    EClass DT = eINSTANCE.getDT();

    /**
     * The meta object literal for the '<em><b>Max depth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DT__MAX_DEPTH = eINSTANCE.getDT_Max_depth();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.RandomForestImpl <em>Random Forest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.RandomForestImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getRandomForest()
     * @generated
     */
    EClass RANDOM_FOREST = eINSTANCE.getRandomForest();

    /**
     * The meta object literal for the '<em><b>Ntree</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM_FOREST__NTREE = eINSTANCE.getRandomForest_Ntree();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.LogisticRegressionImpl <em>Logistic Regression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.LogisticRegressionImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getLogisticRegression()
     * @generated
     */
    EClass LOGISTIC_REGRESSION = eINSTANCE.getLogisticRegression();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGISTIC_REGRESSION__CLASS = eINSTANCE.getLogisticRegression_Class();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.RFormulaImpl <em>RFormula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.RFormulaImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getRFormula()
     * @generated
     */
    EClass RFORMULA = eINSTANCE.getRFormula();

    /**
     * The meta object literal for the '<em><b>Predictive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RFORMULA__PREDICTIVE = eINSTANCE.getRFormula_Predictive();

    /**
     * The meta object literal for the '<em><b>Predictors</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RFORMULA__PREDICTORS = eINSTANCE.getRFormula_Predictors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.XFormulaImpl <em>XFormula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.XFormulaImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getXFormula()
     * @generated
     */
    EClass XFORMULA = eINSTANCE.getXFormula();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XFORMULA__NAME = eINSTANCE.getXFormula_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.AllVariablesImpl <em>All Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.AllVariablesImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getAllVariables()
     * @generated
     */
    EClass ALL_VARIABLES = eINSTANCE.getAllVariables();

    /**
     * The meta object literal for the '<em><b>All</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALL_VARIABLES__ALL = eINSTANCE.getAllVariables_All();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.PredictorVariablesImpl <em>Predictor Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.PredictorVariablesImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getPredictorVariables()
     * @generated
     */
    EClass PREDICTOR_VARIABLES = eINSTANCE.getPredictorVariables();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICTOR_VARIABLES__VARS = eINSTANCE.getPredictorVariables_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.FormulaItemImpl <em>Formula Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.FormulaItemImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getFormulaItem()
     * @generated
     */
    EClass FORMULA_ITEM = eINSTANCE.getFormulaItem();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMULA_ITEM__COLUMN = eINSTANCE.getFormulaItem_Column();

    /**
     * The meta object literal for the '<em><b>Col Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMULA_ITEM__COL_NAME = eINSTANCE.getFormulaItem_ColName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.ValidationImpl <em>Validation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.ValidationImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getValidation()
     * @generated
     */
    EClass VALIDATION = eINSTANCE.getValidation();

    /**
     * The meta object literal for the '<em><b>Stratification</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALIDATION__STRATIFICATION = eINSTANCE.getValidation_Stratification();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATION__METRIC = eINSTANCE.getValidation_Metric();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.StratificationMethodImpl <em>Stratification Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.StratificationMethodImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getStratificationMethod()
     * @generated
     */
    EClass STRATIFICATION_METHOD = eINSTANCE.getStratificationMethod();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.TrainingTestImpl <em>Training Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.TrainingTestImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getTrainingTest()
     * @generated
     */
    EClass TRAINING_TEST = eINSTANCE.getTrainingTest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAINING_TEST__NAME = eINSTANCE.getTrainingTest_Name();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAINING_TEST__NUMBER = eINSTANCE.getTrainingTest_Number();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.CSVSeparator <em>CSV Separator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.CSVSeparator
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCSVSeparator()
     * @generated
     */
    EEnum CSV_SEPARATOR = eINSTANCE.getCSVSeparator();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.FrameworkLang <em>Framework Lang</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.FrameworkLang
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getFrameworkLang()
     * @generated
     */
    EEnum FRAMEWORK_LANG = eINSTANCE.getFrameworkLang();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.SVMKernel <em>SVM Kernel</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.SVMKernel
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVMKernel()
     * @generated
     */
    EEnum SVM_KERNEL = eINSTANCE.getSVMKernel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.SVMClassification <em>SVM Classification</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.SVMClassification
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getSVMClassification()
     * @generated
     */
    EEnum SVM_CLASSIFICATION = eINSTANCE.getSVMClassification();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.CLASS <em>CLASS</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.CLASS
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getCLASS()
     * @generated
     */
    EEnum CLASS = eINSTANCE.getCLASS();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.ValidationMetric <em>Validation Metric</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.ValidationMetric
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getValidationMetric()
     * @generated
     */
    EEnum VALIDATION_METRIC = eINSTANCE.getValidationMetric();

  }

} //MmlPackage
