/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.mml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stratification Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getStratificationMethod()
 * @model
 * @generated
 */
public interface StratificationMethod extends EObject
{
} // StratificationMethod
