/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MmlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MmlStandaloneSetup extends MmlStandaloneSetupGenerated {
  public static void doSetup() {
    new MmlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
